PACKAGE_NAME="amneziawg"
PACKAGE_VERSION="1.0.0"
AUTOINSTALL="no"
BUILT_MODULE_NAME[0]="amneziawg"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make KERNELRELEASE=${kernelver} KERNELDIR=/lib/modules/${kernelver}/build IGNORE_CC_MISMATCH=1"
CLEAN[0]="make KERNELRELEASE=${kernelver} KERNELDIR=/lib/modules/${kernelver}/build clean"
BUILD_EXCLUSIVE_KERNEL="^__KERNEL_ABI_RELEASE__$"
